### ISSUE TITLE
Configure unit test framework for parser

### ISSUE THREAD

**Issue by PFalkowski** [FieryCod/forg#4]
+ Add at least one unit test to showcase the flow

**Comment by FieryCod** [comment]
Since the CIDER does not support REPL test runner for Clojurescript therefore I had to move the tests to `.clj` file. Let me please introduce you to REPL driven testing.

*Prerequisites*
0. Install `leiningen` https://leiningen.org/ then remove and reinstall deps using. rm -Rf node_modules && yarn && lein deps
1. Launch the repl in Calva
![image.png](https://images.zenhubusercontent.com/57bc7528e40e5714b16db80a/db0c01bd-a71e-4f96-b4e5-c312348d4919)
1.1 Choose the first ![image.png](https://images.zenhubusercontent.com/57bc7528e40e5714b16db80a/ef5ba2f4-03ac-4044-9901-00ffd40bc5ce)
1.2 Choose leiningen
![image.png](https://images.zenhubusercontent.com/57bc7528e40e5714b16db80a/f78c3b63-cd10-47a3-b075-71549e19e75a)
1.3 Don't pick any profiles. Just click enter
1.4 In order to run test just navigate to test file and run `Run Tests for Current Namespace`

**Comment by FieryCod** [comment]
Please check whether it works for you
